# Project information
site_name: Project ARC
site_description: Autonomous Recovery Communications is a project based on V2X communications to alert authorities about car accidents
site_author: G1
site_url: http://projectarc.pt

# Opensource thingies
repo_name: projectARC
repo_url: https://github.com/TomsFreitas/projectARC
edit_uri: ""

#Theme stuff
theme: 
  name: material
  custom_dir: html
  feature:
    tabs: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#Navbar
nav:
  - Home: index.md
  #- Personas and Scenarios:
    #- Personas & Scenarios: pers_scen.md
  #- Manual:
    #- Manual: manual.md
  - Technical Aspects:
    - Architecture: arch.md
    #- Requirements: reqs.md
  - Development:
    - How are we going to build this?: development.md
  - Team:                        #tab name
    - Who are we?: about.md   #sub page 1
    - Logbook: logbook.md        #sub page 2


#Plugins, if need be

#Extra CSS & Javascript here, python receives a list of files
    
extra_css: [css/extra.css]
extra_javascript: [js/extra.js]

