# Project information
site_name: Project ARC
site_description: Autonomous Recovery Communications is a project based on V2X communications to alert authorities about car accidents
site_author: G1
site_url: http://projectarc.pt

# Opensource thingies
repo_name: v2x-emergency-site
repo_url: https://github.com/TomsFreitas/v2x-emergency-site
edit_uri: ""

#Theme stuff
theme: 
  name: material
  custom_dir: html
  feature:
    tabs: true

#Navbar
nav:
  - Home: index.md
  - Personas and Scenarios:
    - Personas & Scenarios: pers_scen.md
  - Manual:
    - Manual: manual.md
  - Technical MumboJumbo:
    - Architecture: arch.md
    - Requirements: reqs.md
  - Development:
    - Join our team: development.md
  - Team:                        #tab name
    - About the team: about.md   #sub page 1
    - Logbook: logbook.md        #sub page 2
    - Timesheet: timesheet.md    #sub page 3


#Plugins, if need be

#Extra CSS & Javascript here, python receives a list of files
    
extra_css: [css/extra.css]
extra_javascript: [js/extra.js]

